### PR TITLE
Added login inputs

### PR DESCRIPTION
**Pull request by Souravirus**
screenshot from 2018-11-09 20-40-51

### CODE REVIEW

**Comment by vishichoudhary** [comment]
@Souravirus I have made some changes to the page can you please check .

**Comment by vishichoudhary** [comment]
screenshot from 2018-11-12 03-37-52

**Comment by Souravirus** [comment]
Yeah nice work @vishichoudhary.

**Comment by vishichoudhary** [comment]
I am merging this pr. Some changes required which I think you will take care in next PR

**Pull request merged**
